services:
  my-app:
    build: .
    ports:
      - '3000:3000'
    environment:
      MONGO_DB_USERNAME: /run/secrets/mongo_admin_user
      MONGO_DB_PWD: /run/secrets/mongo_admin_pass
    secrets:
      - mongo_admin_user
      - mongo_admin_pass

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: /run/secrets/mongo_admin_user
      MONGO_INITDB_ROOT_PASSWORD: /run/secrets/mongo_admin_pass
    secrets:
      - mongo_admin_user
      - mongo_admin_pass

  mongo-express:
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: /run/secrets/mongo_admin_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: /run/secrets/mongo_admin_pass
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - 'mongodb'
    secrets:
      - mongo_admin_user
      - mongo_admin_pass

secrets:
  mongo_admin_user:
    file: ./secrets/mongo_admin_user.txt
  mongo_admin_pass:
    file: ./secrets/mongo_admin_pass.txt
